### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by yasinkocak**
Update keywords so we can find this package ;)

### CODE REVIEW

**Comment by ben-eb** [comment]
Do we need the `gulp-cssnano` keyword? That is already a keyword (by virtue of it being the package name). :+1: for `cssnano` keyword though. :smile:

**Comment by yasinkocak** [comment]
I was searching to 'gulp-cssnano' and didn't find also searching for 'cssnano'
I think the index is only on the keywords not on the package name.

**Comment by ben-eb** [comment]
It's the top of the list;

https://www.npmjs.com/search?q=gulp-cssnano

**Comment by yasinkocak** [comment]
Yes, that's right but not on autocomplete at search.

**Comment by ben-eb** [comment]
I think the algorithm is a bit more complex than that; probably counts stars, downloads etc - for example if you start searching for `gulp-autoprefixer` it comes up quickly, and it doesn't have the `gulp-autoprefixer` keyword there (just `autoprefixer`). My gut feeling is that we shouldn't have the package name in there.

https://gitter.im/gulpjs/gulp?at=56ba7ac337ae7622436bc89b

But I am happy to include the keyword for `cssnano`. :smile:

https://github.com/ben-eb/gulp-cssnano/commit/c966ca9c7a30e60380ba110751ccbf83673e4ff1

**Comment by yasinkocak** [comment]
You're right, npmjs has change his algorithm i see.

**Pull request closed without merging**
